# Generated by Django 4.2.1 on 2023-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='percent_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
